### ISSUE TITLE
How did you get around the AR pooling error?

### ISSUE THREAD

**Issue by dam13n** [chashmeetsingh/WebsocketSample#2]
I saw you reference this thread:
https://github.com/rails/rails/issues/23778

I forked your repo to test, and I can send plenty of messages.

But with my own app (built from scratch), I am hitting the limit at 5. I cannot really see any differences...

**Comment by chashmeetsingh** [comment]
hey hi,
add the following to config/environments/development.rb

`ActiveJob::AsyncJob.const_set :DEFAULT_EXECUTOR_OPTIONS,
  ActiveJob::AsyncJob::DEFAULT_EXECUTOR_OPTIONS.merge(min_threads: 0, max_threads: 2, idletime: 10)`

but this is currently a temp fix @dam13n 
or maybe you can try working with beta2

I got the error when I sent too many requests for action cable to handle and it couldn't

**Comment by dam13n** [comment]
Cool, I ended up adding that, and it works. I didn't see it in your code, so I was curious if you had found another workaround.

Also, with this temp fix, make sure to change your adaptor back to "async" for development too. Some odd DB behavior (but not raised errors) came up.

**Comment by chashmeetsingh** [comment]
Some odd DB behavior (but not raised errors) came up. as in??? @dam13n

**Comment by dam13n** [comment]
Haha, sorry. In my case, the transactions would only partially complete. I was trying to update a few different record (vs. just one Message), and it was inconsistent which records updated. I'll add more detail later if it comes up again, but I wanted to at least post a heads up about the adaptor change in case you ran into any problems.

**Comment by chashmeetsingh** [comment]
cool closing this issue :) @dam13n
